### ISSUE TITLE
EPIC: Resident Directory

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/supportive-housing#42]
### Overview
- Staff should be able to see the residents living in the different buildings 
- Staff should be able to perform CRUD operations on residents
- Display the residents in an easy to read format on the frontend

### High-level tasks
- [ ] Add residents table to DB
- [ ]  Query to retrieve all residents
    - [ ]  Need to implement searching for residents by different qualities (ie. name, location, etc.) —> need to figure out if this searching should be done on the frontend or backend
    - [ ]  Add filters
- [ ]  CRUD Operations for residents implemented (and documented)
