### ISSUE TITLE
EPIC: Employee Directory

### ISSUE THREAD

**Issue by safchow** [uwblueprint/supportive-housing#51]
## Summary
Currently, the Employee Directory Page exists as a blank page as part of issue #41. This page should render data only if the user's role is "Admin" and routes the user back to the homepage otherwise. 

Blocked on Figma designs

## Goals
- [ ] Have a clean frontend flow for logins/sign ups
- [ ] Frontend matches Figma designs
- [ ] No weird authentication bugs (ie. it looks like you're signed in when you actually aren't)
- [ ] Flows are different if 2FA is required
- [ ] Errors are displayed when they happen (ie. user not found, user not invited to sign up, invalid 2FA code)

## Implementation
- A db call should be made using the current user's data and return the users role to check if they're an admin
- Using conditional rendering, show the page if they're an admin and an error if they're not
